version: '3.9'

services:
  prediction-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: french-cards-detector:latest
    ports:
      - "9696:9696"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_PATH=models/best.pt
    restart: on-failure
